### ISSUE TITLE
Moodle 3.11, Boost-based theme, Vimeo - Not visible, other rendering issues

### ISSUE THREAD

**Issue by frumbert** [EduardoKrausME/moodle-mod_supervideo#47]
1. I'm trying to embed a Vimeo video on Moodle 3.11 on a Boost-based theme. Without any extra styling, the page only renders the module at 50px high.

![Screenshot 2024-10-25 at 14 37 46](https://github.com/user-attachments/assets/6fa4d721-8d34-43a5-8e91-39af38327788)

I have had to override many of the properties using `!important` CSS rules, as the plugin updates the style tag for the div and iframe, which results in problematic styles, such as the video being too high when the display is very wide.
```scss
#page-mod-supervideo-view #region-main {
    min-height: 100%;
}
#supervideo_area_embed {
--mw: 50vw; // maximum player width
margin: unset !important;
display:flex;
justify-content: center;
align-items: center;
max-width: unset !important;
padding-bottom: unset !important;
    iframe {
      position: relative !important;
      width: var(--mw) !important;
      height: calc(var(--mw) * 9 / 16) !important;
    }
} 
```

2. If I turn off player controls, the vimeo can't be played (even if autoplay is enabled).

3. If I enable to map, it is hidden by the player iframe (it renders behind the iframe, therefore is not visible to the user).

4. The 'Maximum Width for Video Player' setting does not seem to apply for Vimeo embeds.

5. Is there a way to disable the height/max-height properties being updated to the iframe on resize?

6. In 'Distraction-free mode for videos' in my theme there is no way to get back to the course without pressing Back, since primary naviation for my course is in the navbar. Can these settings be made available on a per-instance level rather than globally set for all activities?
